--
--
-- This program is the confidential and proprietary product of 
-- Fast Track Systems, Inc.  Any unauthorized use, reproduction, 
-- or transfer of this program is strictly prohibited.  
-- Copyright (C) 2000 by Fast Track Systems, Inc.  
-- All rights reserved.
-- 
-- $Workfile: migrate_GM_clients_to_1_5.sql$ 
--
-- $Revision: 5$        $Date: 2/27/2008 3:17:44 PM$
--
--
-- Description:  <ADD>
--
---------------------------------------------------------------------
 
<ADD>

---------------------------------------------------------------------
-- MODIFICATION HISTORY:
--
-- $Log: 
--  5    DevTSM    1.4         2/27/2008 3:17:44 PM Debashish Mishra  
--  4    DevTSM    1.3         9/19/2006 12:08:03 AMDebashish Mishra  removed
--       references to obsolete tables
--  3    DevTSM    1.2         3/3/2005 6:33:28 AM  Debashish Mishra   
--  2    DevTSM    1.1         3/3/2005 6:32:19 AM  Debashish Mishra  
--  1    DevTSM    1.0         8/4/2004 2:49:18 PM  Debashish Mishra 
-- $
-- 
---------------------------------------------------------------------
