#!/bin/ksh

. /etc/profile
cd ~oracle
. ./.profile

export load_ctl_dir=/export/home/oracle/cpu_data
export ORA_HOME=/oracle/product/9.0.1



sarfile1=`$ORA_HOME/bin/sqlplus -s dmishra/welcome@devl << EOF
set echo off
set feedback off
set hea off

select '/var/adm/sa/sa'||to_char(sysdate-1,'dd') from dual;
exit;
EOF`

sarfile=`echo $sarfile1`

rsh rossvr3 sar -f $sarfile > $load_ctl_dir/1120_sar
rsh rossvr4 sar -f $sarfile > $load_ctl_dir/1121_sar
rsh rossvr6 sar -f $sarfile > $load_ctl_dir/1042_sar

cat $load_ctl_dir/1120_sar|awk '{print $1}'|grep -v Average|grep -v %idle|grep -v SunOS>$load_ctl_dir/file1
cat $load_ctl_dir/1042_sar|awk '{print $5}'|grep -v Average|grep -v %idle|grep -v sun4u>$load_ctl_dir/file2
cat $load_ctl_dir/1120_sar|awk '{print $5}'|grep -v Average|grep -v %idle|grep -v sun4u>$load_ctl_dir/file3
cat $load_ctl_dir/1121_sar|awk '{print $5}'|grep -v Average|grep -v %idle|grep -v sun4u>$load_ctl_dir/file4


paste -d "|" $load_ctl_dir/file1 $load_ctl_dir/file2 $load_ctl_dir/file3 $load_ctl_dir/file4 | grep -v "|||" > $load_ctl_dir/cpu_data.dat

$ORA_HOME/bin/sqlldr \
CONTROL=$load_ctl_dir/cpu_data.ctl, LOG=$load_ctl_dir/cpu_data.log, \
BAD=$load_ctl_dir/cpu_data.bad, \
USERID=emul/welcome@devl 

