#!/bin/ksh
#
#
# This program is the confidential and proprietary product of 
# Fast Track Systems, Inc.  Any unauthorized use, reproduction, 
# or transfer of this program is strictly prohibited.  
# Copyright (C) 2000 by Fast Track Systems, Inc.  
# All rights reserved.
# 
# $Workfile: backup_emlt.ksh$ 
#
# $Revision: 9$        $Date: 4/11/2002 2:06:06 PM$
#
#
# Description:  Exports the fasttrack schema of devl database
#
#############################################################
 
. /etc/profile

mv /export/home/oracle/tsm10e.dmp /export/home/oracle/tsm10e.dmp.save
rm -rf /export/home/oracle/tsm10e.dmp.save.Z
compress /export/home/oracle/tsm10e.dmp.save

export ORACLE_SID=devl

ORACLE_USER=dmishra
ORACLE_PWD=welcome

/u01/app/oracle/product/9.2.0/bin/exp USERID=$ORACLE_USER/$ORACLE_PWD \
OWNER=ft15e,tsm10e,tsm10e_bgn_2,tsm10e_cvt_2,tsm10e_bay_2,tsm10e_eva_2,tsm10e_fts_2,tsm10e_ft1_2,tsm10e_ft2_2,\
tsm10e_ft3_2,tsm10e_ft4_2,tsm10e_ft5_2,tsm10e_client0,ftcommon \
FILE=/export/home/oracle/tsm10e.dmp \
LOG=/export/home/oracle/backup_tsm10e.log



#############################################################
# MODIFICATION HISTORY:
#
# $Log: 
#  9    DevSource 1.8         4/11/2002 2:06:06 PM Debashish Mishra  
#  8    DevSource 1.7         11/8/2001 11:03:27 AMDebashish Mishra  
#  7    DevSource 1.6         11/8/2001 10:47:24 AMDebashish Mishra Added new TSM
#       schemas 
#  6    DevSource 1.5         7/19/2001 1:33:53 PM Debashish Mishra Changes for
#       fasttrack14a
#  5    DevSource 1.4         6/19/2001 5:12:14 PM Debashish Mishra  
#  4    DevSource 1.3         12/19/2000 7:33:16 PMDebashish Mishra Added entry
#       for fasttrack14
#  3    DevSource 1.2         9/14/2000 3:52:25 PM Debashish Mishra  
#  2    DevSource 1.1         8/29/2000 2:45:18 PM Debashish Mishra Modified for
#       exporting fasttrack13 schema
#  1    DevSource 1.0         5/30/2000 12:32:40 PMDebashish Mishra 
# $
# 
#############################################################
