#!/bin/ksh

export ORACLE_SID=devl

sqlplus -s ftcommon/welcome << EOF

create or replace view CLIENT_DIV as
select ID,CLIENT_ID,NAME,DEF_COUNTRY_ID,DEF_PLAN_CURRENCY_ID,
DEF_OVERHEAD_PCT,DEF_BUDGET_TYPE,CLIENT_DIV_IDENTIFIER,
STARTING_VIEW,COUNTRY_ID,BUILD_TAG_ID,USE_OWN_CNV_FLG,
DEF_PRICE_RANGE,LOGON_TIMEOUT_SECS,
ISO_LANG,USING_WEBSTART,'tsm10' environment from tsm10.client_div;

create or replace view CLIENT_DIV_TO_LIC_APP as
select
ID,CLIENT_DIV_ID,APP_NAME,LICENSE_EXP_DATE,
PRINCIPAL_CONTACT_ID,VERSION,frontend_version,PATCH_AVAILABLE,
'tsm10' environment from tsm10.CLIENT_DIV_TO_LIC_APP;

create or replace view FTGROUP as
select
id, name,'tsm10' environment from ft15.ftgroup;

create or replace view FTUSER as
select
ID,NAME||'@tsm10' name ,PASSWORD,SITE_ID,STARTING_SCREEN,LAST_PASSWORD_UPDATE,
FIRST_NAME,LAST_NAME,LAST_LOGIN_DATE,PRIMARY_TA_ID,ADDRESS_LINE_1,
ADDRESS_LINE_2,CITY,STATE,POSTAL_CODE,COUNTRY,WORK_PHONE,
HOME_PHONE,FAX,MOBILE_PHONE,EMAIL,PREFERRED_CONTACT,TITLE,
CLIENT_ID,CLIENT_DIV_ID,DISPLAY_NAME,ACTIVE_TRACE_USER,
ACTIVE_TSM_USER,'tsm10' environment from ft15.ftuser;

create or replace view FTUSER_TO_CLIENT_GROUP as
select
ID,CLIENT_GROUP_ID,FTUSER_ID,'tsm10' environment
from tsm10.ftuser_to_client_group;

create or replace view FTUSER_TO_FTGROUP as
select
id,ftuser_id,ftgroup_id,'tsm10' environment from
ft15.ftuser_to_ftgroup;


EOF


sqlplus -s dmishra/welcome <<EOF

drop user ft15e cascade;
drop user TSM10E cascade; 
drop user TSM10E_BAY_2 cascade; 
drop user TSM10E_BGN_2 cascade; 
drop user TSM10E_CLIENT0 cascade; 
drop user TSM10E_CVT_2 cascade; 
drop user TSM10E_EVA_2 cascade; 
drop user TSM10E_FT1_2 cascade; 
drop user TSM10E_FT2_2 cascade; 
drop user TSM10E_FT3_2 cascade; 
drop user TSM10E_FT4_2 cascade; 
drop user TSM10E_FT5_2 cascade; 
drop user TSM10E_FTS_2 cascade;

create user ft15e identified by welcome default tablespace ftsmall temporary tablespace temp;
create user TSM10E identified by welcome default tablespace tsmsmall temporary tablespace temp;
create user TSM10E_BAY_2 identified by welcome default tablespace tsmsmall temporary tablespace temp;
create user TSM10E_BGN_2 identified by welcome default tablespace tsmsmall temporary tablespace temp;
create user TSM10E_CLIENT0 identified by welcome default tablespace tsmsmall temporary tablespace temp;
create user TSM10E_CVT_2 identified by welcome default tablespace tsmsmall temporary tablespace temp;
create user TSM10E_EVA_2 identified by welcome default tablespace tsmsmall temporary tablespace temp;
create user TSM10E_FT1_2 identified by welcome default tablespace tsmsmall temporary tablespace temp;
create user TSM10E_FT2_2 identified by welcome default tablespace tsmsmall temporary tablespace temp;
create user TSM10E_FT3_2 identified by welcome default tablespace tsmsmall temporary tablespace temp;
create user TSM10E_FT4_2 identified by welcome default tablespace tsmsmall temporary tablespace temp;
create user TSM10E_FT5_2 identified by welcome default tablespace tsmsmall temporary tablespace temp;
create user TSM10E_FTS_2 identified by welcome default tablespace tsmsmall temporary tablespace temp;

grant connect,resource to ft15e;
grant connect,resource to TSM10E; 
grant connect,resource to TSM10E_BAY_2; 
grant connect,resource to TSM10E_BGN_2; 
grant connect,resource to TSM10E_CLIENT0; 
grant connect,resource to TSM10E_CVT_2; 
grant connect,resource to TSM10E_EVA_2; 
grant connect,resource to TSM10E_FT1_2; 
grant connect,resource to TSM10E_FT2_2;
grant connect,resource to TSM10E_FT3_2; 
grant connect,resource to TSM10E_FT4_2; 
grant connect,resource to TSM10E_FT5_2; 
grant connect,resource to TSM10E_FTS_2; 

exit;
EOF

imp dmishra/welcome file=/export/home/oracle/tsm10e.dmp fromuser=ft15e,TSM10E,TSM10E_BAY_2,TSM10E_BGN_2,TSM10E_CLIENT0,TSM10E_CVT_2,TSM10E_EVA_2,TSM10E_FT1_2,TSM10E_FT2_2,TSM10E_FT3_2,TSM10E_FT4_2,TSM10E_FT5_2,TSM10E_FTS_2 touser=ft15e,TSM10E,TSM10E_BAY_2,TSM10E_BGN_2,TSM10E_CLIENT0,TSM10E_CVT_2,TSM10E_EVA_2,TSM10E_FT1_2,TSM10E_FT2_2,TSM10E_FT3_2,TSM10E_FT4_2,TSM10E_FT5_2,TSM10E_FTS_2


sqlplus -s ftcommon/welcome << EOF

create or replace view CLIENT_DIV as
select ID,CLIENT_ID,NAME,DEF_COUNTRY_ID,DEF_PLAN_CURRENCY_ID,
DEF_OVERHEAD_PCT,DEF_BUDGET_TYPE,CLIENT_DIV_IDENTIFIER,
STARTING_VIEW,COUNTRY_ID,BUILD_TAG_ID,USE_OWN_CNV_FLG,
DEF_PRICE_RANGE,LOGON_TIMEOUT_SECS,
ISO_LANG,USING_WEBSTART,'tsm10' environment from tsm10.client_div
union all
select ID,CLIENT_ID,NAME,DEF_COUNTRY_ID,DEF_PLAN_CURRENCY_ID,
DEF_OVERHEAD_PCT,DEF_BUDGET_TYPE,CLIENT_DIV_IDENTIFIER,
STARTING_VIEW,COUNTRY_ID,BUILD_TAG_ID,USE_OWN_CNV_FLG,
DEF_PRICE_RANGE,LOGON_TIMEOUT_SECS,
ISO_LANG,USING_WEBSTART,'tsm10e' environment from tsm10e.client_div;

create or replace view CLIENT_DIV_TO_LIC_APP as
select ID,CLIENT_DIV_ID,APP_NAME,LICENSE_EXP_DATE,
PRINCIPAL_CONTACT_ID,VERSION,frontend_version,PATCH_AVAILABLE,
'tsm10' environment from tsm10.CLIENT_DIV_TO_LIC_APP
union all
select ID,CLIENT_DIV_ID,APP_NAME,LICENSE_EXP_DATE,
PRINCIPAL_CONTACT_ID,VERSION,frontend_version,PATCH_AVAILABLE,
'tsm10e' environment from tsm10e.CLIENT_DIV_TO_LIC_APP;

create or replace view FTGROUP as
select id, name,'tsm10' environment from ft15.ftgroup
union all
select id, name,'tsm10e' environment from ft15e.ftgroup;

create or replace view FTUSER as
select ID,NAME||'@tsm10' name ,PASSWORD,SITE_ID,STARTING_SCREEN,LAST_PASSWORD_UPDATE,
FIRST_NAME,LAST_NAME,LAST_LOGIN_DATE,PRIMARY_TA_ID,ADDRESS_LINE_1,
ADDRESS_LINE_2,CITY,STATE,POSTAL_CODE,COUNTRY,WORK_PHONE,
HOME_PHONE,FAX,MOBILE_PHONE,EMAIL,PREFERRED_CONTACT,TITLE,
CLIENT_ID,CLIENT_DIV_ID,DISPLAY_NAME,ACTIVE_TRACE_USER,
ACTIVE_TSM_USER,'tsm10' environment from ft15.ftuser
union all
select ID,NAME||'@tsm10e' name ,PASSWORD,SITE_ID,STARTING_SCREEN,LAST_PASSWORD_UPDATE,
FIRST_NAME,LAST_NAME,LAST_LOGIN_DATE,PRIMARY_TA_ID,ADDRESS_LINE_1,
ADDRESS_LINE_2,CITY,STATE,POSTAL_CODE,COUNTRY,WORK_PHONE,
HOME_PHONE,FAX,MOBILE_PHONE,EMAIL,PREFERRED_CONTACT,TITLE,
CLIENT_ID,CLIENT_DIV_ID,DISPLAY_NAME,ACTIVE_TRACE_USER,
ACTIVE_TSM_USER,'tsm10e' environment from ft15e.ftuser;

create or replace view FTUSER_TO_CLIENT_GROUP as
select ID,CLIENT_GROUP_ID,FTUSER_ID,'tsm10' environment
from tsm10.ftuser_to_client_group
union all
select ID,CLIENT_GROUP_ID,FTUSER_ID,'tsm10e' environment
from tsm10e.ftuser_to_client_group;

create or replace view FTUSER_TO_FTGROUP as
select id,ftuser_id,ftgroup_id,'tsm10' environment from
ft15.ftuser_to_ftgroup
union all
select id,ftuser_id,ftgroup_id,'tsm10e' environment from
ft15e.ftuser_to_ftgroup;

exit;

EOF
