update country set is_pbt_viewable=0;
update country set is_pbt_viewable=1 where lower(name)=lower('Austria');
update country set is_pbt_viewable=1 where lower(name)=lower('Belgium');
update country set is_pbt_viewable=1 where lower(name)=lower('Canada');
update country set is_pbt_viewable=1 where lower(name)=lower('France');
update country set is_pbt_viewable=1 where lower(name)=lower('Germany');
update country set is_pbt_viewable=1 where lower(name)=lower('Ireland');
update country set is_pbt_viewable=1 where lower(name)=lower('Israel');
update country set is_pbt_viewable=1 where lower(name)=lower('Italy');
update country set is_pbt_viewable=1 where lower(name)=lower('Netherlands');
update country set is_pbt_viewable=1 where lower(name)=lower('South Africa');
update country set is_pbt_viewable=1 where lower(name)=lower('Spain');
update country set is_pbt_viewable=1 where lower(name)=lower('Sweden');
update country set is_pbt_viewable=1 where lower(name)=lower('Switzerland');
update country set is_pbt_viewable=1 where lower(name)=lower('United Kingdom');
update country set is_pbt_viewable=1 where lower(name)=lower('United States');
update country set is_pbt_viewable=1 where lower(name)=lower('Eastern Europe');
update country set is_pbt_viewable=1 where lower(name)=lower('North America');
update country set is_pbt_viewable=1 where lower(name)=lower('Europe');
update country set is_pbt_viewable=1 where lower(name)=lower('Scandinavia');
update country set is_pbt_viewable=1 where lower(name)=lower('Latin America');
update country set is_pbt_viewable=1 where lower(name)=lower('Western Europe');
update country set is_pbt_viewable=1 where lower(name)=lower('Pacific Asia');
update country set is_pbt_viewable=1 where lower(name)=lower('Middle East/Africa');
